### ISSUE TITLE
script stopped working for some reason.

### ISSUE THREAD

**Issue by italianjesus** [patxijuaristi/website_email_scraper#3]
the exe version works but the .py version shows up nothing.

![Screenshot_1](https://user-images.githubusercontent.com/54536994/159025486-46ba7927-29af-4f20-910b-6ffd7b7e339e.png)

**Comment by patxijuaristi** [comment]
Hi! The script name is nor "scraper.py", it's **email_scraper.py** or **email_scraper_without_crawling.py**. So maybe you have done some changes that is causing some issues.

**Comment by italianjesus** [comment]
It worked after I changed it for some time, but it stopped working.

**Comment by italianjesus** [comment]
I tried it with the untouched download and its the same result 

![image](https://user-images.githubusercontent.com/54536994/159027517-b1cbe1ea-3e32-47ad-9f60-2186550d7685.png)
